version: "3"
services:
    app:
        image: nginx:latest
        depends_on:
           - db
        ports:
            - "8080:80"
        volumes:
            - ./:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            default:
                ipv4_address: 172.20.1.4
        links:
            - php
    db:
       image: mariadb
       volumes:
        - /data/mariadb:/var/lib/mysql
       tmpfs:
          - /tmp
          - /run/mysqld
          - /var/run
       environment:
          - MYSQL_ROOT_PASSWORD
          - MYSQL_DATABASE
          - MYSQL_USER
          - MYSQL_PASSWORD
       security_opt:
         - no-new-privileges
       networks:
        default:
           ipv4_address: 172.20.1.3
       read_only: true
    php:
        image: php:7-fpm
        volumes:
        - ./:/code

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.1.0/24
